[project]
name = "red-teaming-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx[http2]>=0.28.1",
    "logfire>=4.11.0",
    "pydantic-ai>=1.0.15",
]
